version: '3.9'

services:



  patient-db:
    image: postgres:15
    container_name: patient-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: patient_db
    ports:
      - "5434:5432"
    volumes:
      - ./patient-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  doctor-db:
    image: postgres:15
    container_name: doctor-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: doctor_db
    ports:
      - "5435:5432"
    volumes:
      - ./doctor-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  appointment-db:
    image: postgres:15
    container_name: appointment-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appointment_db
    ports:
      - "5436:5432"
    volumes:
      - ./appointment-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      TZ: Asia/Ho_Chi_Minh
    PGTZ: Asia/Ho_Chi_Minh
    ports:
      - "5433:5432"
    volumes:
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
	- ./postgresql.conf:/etc/postgresql/postgresql.conf
