server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_patient?createDatabaseIfNotExist=true
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
