spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db?serverTimezone=Asia/Ho_Chi_Minh
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    open-in-view: false  # Điều này giúp tránh vấn đề với LazyInitializationException trong ứng dụng

jwt:
  secret: mysecretkey123456
  expiration: 86400000

server:
  port: 8081
