server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**
        - id: patient-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/patients/**
        - id: doctor-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/doctors/**
        - id: appointment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/appointments/**
      default-filters:
        - AddResponseHeader=X-Gateway, HospitalBookingGateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
